### ISSUE TITLE
 Running Jetpack plugin makes wp-video-embed-privacy stop working

### ISSUE THREAD

**Issue by ZAS-ONE** [michaelzangl/wp-video-embed-privacy#14]
I have everything done like explained and it won't work. 

I run it on a Word Press site (example: https://www.vonguteneltern.de/fragen-an-die-hebamme-34-wie-bereite-ich-mich-aufs-stillen-vor/). 

Checked:
- enable url_allow_fopen is running
- links are posted correctly
- I run Soledad theme
- Cloudflare is active 
- I tried switching off most other plugins, still won't work

Anyone any ideas?

Thanks, Christian

**Comment by michaelzangl** [comment]
Any of the plugins / themes you installed is already taking care of the YT videos in an other way.

It adds a 
```
<span class="embed-youtube" style="text-align:center; display: block;">
```

This might help you find it.

**Comment by ZAS-ONE** [comment]
It is actually caused by Jetpack, it seems. After having switched that off, it at least works but looks bad. (black bars and weird sizing of player). If you can figure out what inside Jetpack causes this, that would be ace. Many people use it, should be valuable.

**Comment by ZAS-ONE** [comment]
Also, if you look now, aside from the black bars the whole video is way to big after you clicked to play. There is only half of the actual screen visible and it looks very bad on mobile. It is not responsive at all sadly for me.

**Comment by michaelzangl** [comment]
If someone uses jetpack, they usually don't really care about the privacy of their users, so most of the people using it won't be interested in this plugin.

The width/height is set by wordpress on the youtube frame, the plugin just takes the height that was set originally.

**Comment by ZAS-ONE** [comment]
> If someone uses jetpack, they usually don't really care about the privacy of their users, so most of the people using it won't be interested in this plugin.
This is really not a good "excuse", I am sure (or hope) people will understand the need, even if they use Jetpack (for stats and some "most read" widgets only, in my case for example). 

And do you have an idea why the video itself is so huge inside the player (on mobile settings) mainly.

**Comment by michaelzangl** [comment]
No, I don't know which plugin sets the width of that video.

**Comment by michaelzangl** [comment]
Closing as "won't fix" - we don't need jetpack compatibility.
