### ISSUE TITLE
Kein Vorschaubild

### ISSUE THREAD

**Issue by MarkRotNF** [michaelzangl/wp-video-embed-privacy#15]
Es wird nur eine schwarzes Bild hinter dem Text angezeigt, kein Vorschaubild (thumbnail).

**Comment by enoversum** [comment]
Hier leider dasselbe :(.

**Comment by michaelzangl** [comment]
Gibt es eine Beispielinstallation oder irgend eine Fehlermeldung?

**Comment by MarkRotNF** [comment]
Nein keine Fehlermeldung. https://markrot-nf.de etwas nach unten scrollen; oben mit Einbettungslink ohne Plugin (mit Vorschaubild) und darunter mit Plugin (ohne Vorschaubild).

**Comment by michaelzangl** [comment]
@MarkRotNF Du solltest deinen Server umkonfigurieren und keinen Verzeichnisindex mehr erlauben (`-Indexes`)

Kann es sein dass `mod_rewrite` auf dem Server deaktiviert ist?

**Comment by MarkRotNF** [comment]
Es war aktiviert, aber in der Config war es falsch eingetragen. Geht jetzt. Danke!
Danke für den Info! :D
