### ISSUE TITLE
Version 2.1 showing numeric key in frontend

### ISSUE THREAD

**Issue by sangallo** [michaelzangl/wp-video-embed-privacy#6]
I tried out release 2.1. - it works fine for me. But after clicking on "Play" a numeric key appears directly below the video. How do I get rid of it?

**Comment by michaelzangl** [comment]
Which key is displayed below the video? Do you have a sample site?

**Comment by sangallo** [comment]
You may have a loook here: https://www.tauchjournal.de/globale-erwaermung-veraendert-das-great-barrier-riff-15350 <https://www.tauchjournal.de/globale-erwaermung-veraendert-das-great-barrier-riff-15350>
_________________________
Olaf Klodt
Journalist & Architekturhistoriker
Kirchenweg 6
25992 List/Sylt
Tel. 04651 - 832 09 20
olaf@klodt.info
www.klodt.info
www.tauchjournal.de

**Comment by michaelzangl** [comment]
Thanks for testing. Should be better now.
