### ISSUE TITLE
Caching...wie aktivieren?

### ISSUE THREAD

**Issue by Gerdski** [michaelzangl/wp-video-embed-privacy#9]
Hallo,

ich versuche, das Caching der Vorschaubilder zu aktivieren. Der Haken ist gesetzt bei den Plugin-Einstellungen. Aber ich stehe total auf dem Schlauch.

In den FAQs heißt es

> Can I enable caching
> Yes, rename the file in the video-embed-privacy/preview directory

Welches File muß ich denn umbenennen, und wie muß es heißen? 

Danke!

**Comment by michaelzangl** [comment]
Das ist noch alt - in der aktuellen Pre-Release gibt es nur den Haken, das wars schon.

**Comment by Gerdski** [comment]
OK...der Haken ist gesetzt, aber ich sehe bei jedem Video trotzdem immer nur einen schwarzen Hintergrund, und in der Mitte den dicken roten YouTube-Pfeilbutton. Was mache ich falsch?

![grafik](https://user-images.githubusercontent.com/39156455/39911421-a0f75956-54fb-11e8-979f-b6f3b792b71e.png)

**Comment by michaelzangl** [comment]
Das ist dann ein anderes Problem. Wahrscheinlich hat der Server Probleme die Bilder von Youtube zu laden - dafür braucht er die Möglichkeit HTTP-Anfragen zu senden. Welche Version verwendest du?

**Comment by Gerdski** [comment]
2.0

**Comment by Gerdski** [comment]
Wo könnte denn das Problem liegen?
